### ISSUE TITLE
Come up with a method of organizing repo

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/edd-cli-tools#2]
Before prs are opened to add tons of new commands, it'd be nice to layout how these commands should be laid out in terms of files, cli function naming, etc, so that it'll be manageable. 

Opening a ticket to start that discussion. The agreed upon method should be put in the readme file

**Comment by pippinsplugins** [comment]
I vote we do it very similar to how the library of code snippets works. A folder or file for each extension / "category" of command.

**Comment by phpbits** [comment]
@pippinsplugins  I'm on the process of migrating my products to another domain as well. Will this work on the latest EDD version? Thanks!
